In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("dataset_facebook.csv",delimiter=';') 
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [3]:
df.shape

(500, 19)

In [4]:
subset1=df[['Type','Category','Post Month']]  #Getting the subsets from the main dataset
print(subset1.head())

     Type  Category  Post Month
0   Photo         2          12
1  Status         2          12
2   Photo         3          12
3   Photo         2          12
4   Photo         2          12

In [5]:
subset2=df[['comment','Post Weekday','like']] 
print(subset2.head())

   comment  Post Weekday    like
0        4             4    79.0
1        5             3   130.0
2        0             3    66.0
3       58             2  1572.0
4       19             2   325.0

In [6]:
# Merging the dataset now as the requirement 2 of the problem statement  
merged=pd.concat([subset1,subset2],axis=1)
print(merged.head())

     Type  Category  Post Month  comment  Post Weekday    like
0   Photo         2          12        4             4    79.0
1  Status         2          12        5             3   130.0
2   Photo         3          12        0             3    66.0
3   Photo         2          12       58             2  1572.0
4   Photo         2          12       19             2   325.0

In [9]:
# Sorting the values on the basis of the likes 
sorted_df=df.sort_values(by=['like'],ascending=False) 
sorted_df.head(10)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174

In [13]:
# Transposing the dataset values 
Transposed_dataset=df.head().transpose() 
Transposed_dataset.head()

                       0       1       2       3       4
Page total likes  139441  139441  139441  139441  139441
Type               Photo  Status   Photo   Photo   Photo
Category               2       2       3       2       2
Post Month            12      12      12      12      12
Post Weekday           4       3       3       2       2

In [16]:
import numpy as np 
# Changing the dataset dimensions(i.e. Reshaping)
arr=np.array(df[['Post Month','Post Weekday']].head(6)) 
reshaped=arr.reshape(3,4) 
reshaped

array([[12,  4, 12,  3],
       [12,  3, 12,  2],
       [12,  2, 12,  1]])